import pandas as pd

def calcAverage(csv):
    # Read the data into a pandas DataFrame
    df = pd.read_csv(csv)

    # Replace non-numeric values with NaN
    df_numeric = df.drop(columns=['group']).apply(pd.to_numeric, errors='coerce')

    # Calculate the average for each course column, skipping NaN values
    averages = df_numeric.mean()

    # Create a new row with the averages
    average_row = pd.DataFrame(averages).transpose()

    # Set the group column value for the average row
    average_row['group'] = 'average'

    # Append the average row to the original DataFrame
    df = pd.concat([df, average_row], ignore_index=True)

    # Save the updated DataFrame to a new CSV file
    df.to_csv(csv, index=False)

    print("Averages appended and CSV file updated.")

calcAverage('vsk21aFysiikka.csv')
calcAverage('vsk21aKemia.csv')
calcAverage('vsk21aLbi.csv')
calcAverage('vsk21almaa.csv')
calcAverage('vsk21aLmab.csv')
calcAverage('vsk21bFysiikka.csv')
calcAverage('vsk21bKemia.csv')
calcAverage('vsk21bLbi.csv')
calcAverage('vsk21blmaa.csv')
calcAverage('vsk21bLmab.csv')
calcAverage('vsk21cFysiikka.csv')
calcAverage('vsk21cKemia.csv')
calcAverage('vsk21cLbi.csv')
calcAverage('vsk21clmaa.csv')
calcAverage('vsk21cLmab.csv')
calcAverage('vsk21dFysiikka.csv')
calcAverage('vsk21dKemia.csv')
calcAverage('vsk21dLbi.csv')
calcAverage('vsk21dlmaa.csv')
calcAverage('vsk21dLmab.csv')
calcAverage('vsk21eFysiikka.csv')
calcAverage('vsk21eKemia.csv')
calcAverage('vsk21eLbi.csv')
calcAverage('vsk21elmaa.csv')
calcAverage('vsk21eLmab.csv')
calcAverage('vsk22aFysiikka.csv')
calcAverage('vsk22aKemia.csv')
calcAverage('vsk22aLbi.csv')
calcAverage('vsk22almaa.csv')
calcAverage('vsk22aLmab.csv')
calcAverage('vsk22bFysiikka.csv')
calcAverage('vsk22bKemia.csv')
calcAverage('vsk22bLbi.csv')
calcAverage('vsk22blmaa.csv')
calcAverage('vsk22bLmab.csv')
calcAverage('vsk22cFysiikka.csv')
calcAverage('vsk22cKemia.csv')
calcAverage('vsk22cLbi.csv')
calcAverage('vsk22clmaa.csv')
calcAverage('vsk22cLmab.csv')
calcAverage('vsk22dFysiikka.csv')
calcAverage('vsk22dKemia.csv')
calcAverage('vsk22dLbi.csv')
calcAverage('vsk22dlmaa.csv')
calcAverage('vsk22dLmab.csv')
calcAverage('vsk22eFysiikka.csv')
calcAverage('vsk22eKemia.csv')
calcAverage('vsk22eLbi.csv')
calcAverage('vsk22elmaa.csv')
calcAverage('vsk22eLmab.csv')
calcAverage('vsk22fFysiikka.csv')
calcAverage('vsk22fKemia.csv')
calcAverage('vsk22fLbi.csv')
calcAverage('vsk22flmaa.csv')
calcAverage('vsk22fLmab.csv')
calcAverage('vsk23aFysiikka.csv')
calcAverage('vsk23aKemia.csv')
calcAverage('vsk23aLbi.csv')
calcAverage('vsk23almaa.csv')
calcAverage('vsk23aLmab.csv')
calcAverage('vsk23bFysiikka.csv')
calcAverage('vsk23bKemia.csv')
calcAverage('vsk23bLbi.csv')
calcAverage('vsk23blmaa.csv')
calcAverage('vsk23bLmab.csv')
calcAverage('vsk23cFysiikka.csv')
calcAverage('vsk23cKemia.csv')
calcAverage('vsk23cLbi.csv')
calcAverage('vsk23clmaa.csv')
calcAverage('vsk23cLmab.csv')
calcAverage('vsk23dFysiikka.csv')
calcAverage('vsk23dKemia.csv')
calcAverage('vsk23dLbi.csv')
calcAverage('vsk23dlmaa.csv')
calcAverage('vsk23dLmab.csv')
calcAverage('vsk23eFysiikka.csv')
calcAverage('vsk23eKemia.csv')
calcAverage('vsk23eLbi.csv')
calcAverage('vsk23elmaa.csv')
calcAverage('vsk23eLmab.csv')
calcAverage('vsk23fFysiikka.csv')
calcAverage('vsk23fKemia.csv')
calcAverage('vsk23fLbi.csv')
calcAverage('vsk23flmaa.csv')
calcAverage('vsk23fLmab.csv')
calcAverage('vsk23vFysiikka.csv')
calcAverage('vsk23vKemia.csv')
calcAverage('vsk23vLbi.csv')
calcAverage('vsk23vlmaa.csv')
calcAverage('vsk23vLmab.csv')

